Repository ridi/books-frontend, pull requests merged in 2020-05, with the labels that each got.

#251 connected-next-router 제거
  package.json
  src/pages/_app.tsx
  src/store/config.ts
  src/store/reducers.ts
  src/types/connected-next-router/index.d.ts
  yarn.lock
Labels: refactor

#252 RIDIBOOKS 로고를 h1 으로 감쌈, inline svg 삭제
  src/assets/svg/RidiLogo.svg
  src/assets/svg/RidiSelectLogo.svg
  src/components/GNB/index.tsx
  src/constants/icons.ts
  src/tests/pages/partials/gnb/Index.spec.tsx
Labels: a11y, styling

#240 검색 LandscapeBook (1)
  src/components/Book/SearchLandscapeBook.tsx
  src/components/Tabs/SearchCategoryTab.tsx
  src/pages/search/index.tsx
  src/services/books/reducer.ts
  src/services/books/request.ts
  src/services/books/saga.ts
  src/services/category/reducer.ts
  src/services/category/saga.ts
  src/svgs/Star.svg
  src/tests/pages/GenreHome.spec.tsx
  src/tests/pages/search/searchResult.fixture.json
  src/types/book.ts
  src/types/searchResults.ts
Labels: styling

#250 검색 페이지 페이지네이션
  src/components/Pagination/Pagination.tsx
  src/components/Tabs/SearchCategoryTab.tsx
  src/pages/search/index.tsx
  src/svgs/More.svg
  src/tests/pages/search/Index.spec.tsx
Labels: styling

#253 searchResult Runtypes 적용
  src/components/Search/InstantSearch.tsx
  src/components/Search/InstantSearchResult.tsx
  src/components/Search/types.ts
  src/pages/search/index.tsx
  src/types/searchResults.ts
  src/utils/sentry.ts
Labels: enhancement, refactor

#254 사용하지 않는 패키지 정리
  package.json
  src/types/common.ts
  yarn.lock
Labels: refactor

#257 폴리필이 Edge 18에서 충분히 되도록 함
  package.json
  src/polyfills.js
  yarn.lock
Labels: hotfix

#255 정렬 filter 추가
  src/assets/svg/CaretDown.svg
  src/constants/icons.ts
  src/pages/search/FilterSelector.tsx
  src/pages/search/index.tsx
  src/types/searchResults.ts
Labels: feature, styling

#260 도서 상세 정보를 필요할 때 꺼내오도록 함
  src/components/Book/PortraitBook.tsx
  src/components/Book/SearchLandscapeBook.tsx
  src/components/Book/ThumbnailWithBadge.tsx
  src/components/BookMeta/BookMeta.tsx
  src/components/BookMeta/index.tsx
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBookCarousel.tsx
  src/components/BookSections/SelectionBook/SelectionBookItem.tsx
  src/components/BookSections/SelectionBook/SelectionBookList.tsx
  src/components/BookSections/SelectionBook/index.tsx
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
  src/components/RecommendedBook/BookMeta.tsx
  src/components/RecommendedBook/RecommendedBookCarousel.tsx
  src/components/RecommendedBook/RecommendedBookItem.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
  src/components/RecommendedBook/index.tsx
  src/hooks/useBookDetailSelector.ts
  src/tests/components/BookSelections/SelectionBook.spec.tsx
  src/tests/components/MultipleLineBook/MultipleLineBookComponent.spec.tsx
  src/tests/components/RecommendedBook/RecommendedBook.spec.tsx
  src/types/sections.ts
Labels: enhancement, refactor

#263 올바른 위치로 컴포넌트 파일 이동
  src/components/Search/FilterSelector.tsx
  src/pages/search/index.tsx
Labels: bug

#264 디자인 QA 1차 적용
  src/components/Book/SearchLandscapeBook.tsx
  src/components/Tabs/SearchCategoryTab.tsx
  src/pages/search/index.tsx
Labels: styling

#262 fix/parent_category_name 이 null 일 경우 2차 카테고리 표시
  src/components/Book/SearchLandscapeBook.tsx
Labels: bug

#261 검색 상세 페이지 성인 제외 필터
  src/assets/svg/Check.svg
  src/components/Search/AdultExcludeToggle.tsx
  src/components/Search/index.ts
  src/constants/icons.ts
  src/pages/search/index.tsx
Labels: feature, styling

#268 도서 없는 경우 화면 추가
  src/pages/search/index.tsx
Labels: styling

#273 검색 contents 영역 최소 높이 추가
  src/pages/search/index.tsx
Labels: styling

#267 0이하 페이지 또는 max page(400) 이상 이동 방어코드 추가
  src/components/Pagination/Pagination.tsx
  src/pages/search/index.tsx
Labels: bug

#276 로딩 placeholder 추가
  src/components/Book/SearchLandscapeBook.tsx
Labels: styling

#275 카테고리 탭 스크롤 수정
  src/components/Pagination/Pagination.tsx
  src/components/ScrollContainer.tsx
  src/components/Tabs/SearchCategoryTab.tsx
  src/hooks/useScrollPosition.ts
  src/hooks/useScrollSlider.ts
  src/pages/search/index.tsx
Labels: enhancement, styling

#270 디자인 QA 2차 반영
  src/components/Book/SearchLandscapeBook.tsx
  src/components/Tabs/SearchCategoryTab.tsx
  src/pages/search/index.tsx
Labels: styling

#272 썸네일, 대여 배지 표시 오류 수정, 렌트 가격 일부 조정
  src/components/Book/SearchLandscapeBook.tsx
  src/components/Book/ThumbnailWithBadge.tsx
  src/utils/books.ts
  src/utils/common.ts
Labels: bug

#277 RankingBook 높이 제한 추가
  src/components/BookSections/RankingBook/RankingBookList.tsx
Labels: hotfix, styling

#278 RankingBook 높이 제한 추가 (bp #277)
  src/components/BookSections/RankingBook/RankingBookList.tsx
Labels: BackPort

#269 인스턴트 검색에 성인제외 버튼 추가
  src/components/Pagination/Pagination.tsx
  src/components/Search/InstantSearch.tsx
  src/components/Search/InstantSearchResult.tsx
  src/components/Switch/Switch.tsx
  src/tests/components/Search/InstantSearch.spec.tsx
Labels: feature, styling

#279 가격 정보 표시 수정
  src/components/Book/SearchLandscapeBook.tsx
Labels: bug

#282 도서 평점 표시할 때 정수도 .0 까지 표시하도록 수정(4 -> 4.0)
  src/components/Book/SearchLandscapeBook.tsx
Labels: bug

#284 인스턴트 검색 올바른 순서로 저자 표시
  src/components/Search/InstantSearchResult.tsx
Labels: bug

#285 도서 unit 올바르게 표시, 체험판을 제외한 총 권수 표시
  src/components/Book/SearchLandscapeBook.tsx
Labels: bug

#286 hotfix/transpileModules entities 포함(IE11 대응)
  next.config.js
Labels: hotfix

#281 가격 표시 컴포넌트 테스트 추가
  src/components/Book/SearchLandscapeBook.tsx
  src/tests/components/Book/PriceInfo.spec.tsx
  src/types/book.ts
Labels: testing

#283 작가 이름 표시 및 앵커 처리
  src/components/Book/SearchLandscapeBook.tsx
Labels: styling

#280 카테고리 탭 캐넘버 스타일 변경
  src/components/Carousel/Arrow.tsx
  src/components/ScrollContainer.tsx
  src/components/Tabs/SearchCategoryTab.tsx
Labels: styling

#291 카테고리 클릭시 is_login params 가 붙는걸 막음
  src/components/Tabs/SearchCategoryTab.tsx
Labels: bug

#294 effect 에 isAdultExclude 도 체크하여 가장 마지막 페이지로 보냄
  src/pages/search/index.tsx
Labels: bug

#297 InstantSearch 리팩토링 (1)
  src/components/Search/InstantSearch.tsx
  src/components/Search/InstantSearchHistory.tsx
  src/components/Search/InstantSearchResult.tsx
Labels: enhancement, refactor

#295 도서 Display 트래킹 slug 수정
  src/components/Book/SearchLandscapeBook.tsx
Labels: tracking

#298 hotfix/올바른 표지 id 사용
  src/tests/components/BookSelections/RankingBookList.spec.tsx
  src/tests/components/BookSelections/SelectionBook.spec.tsx
  src/tests/components/RecommendedBook/RecommendedBook.spec.tsx
  src/tests/pages/GenreHome.spec.tsx
  src/utils/books.ts
Labels: hotfix

#296 정가 표시 않도록 수정
  src/components/Book/SearchLandscapeBook.tsx
Labels: temporary

#293 디자인 QA 반영 3
  src/components/Book/SearchLandscapeBook.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Search/AdultExcludeToggle.tsx
  src/components/Search/FilterSelector.tsx
  src/components/Search/InstantSearch.tsx
  src/components/Tabs/SearchCategoryTab.tsx
  src/pages/search/index.tsx
  src/styles/index.ts
Labels: styling

#300 IE11 QA-1
  src/components/Pagination/Pagination.tsx
  src/pages/search/index.tsx
Labels: bug, ie11

#304 라우터 변경됐을 때 q 확인하여 인스턴트 검색어로 추가
  src/components/Book/SearchLandscapeBook.tsx
  src/components/Search/InstantSearch.tsx
Labels: bug

#303 anchor 에 href 추가(tab 이동 가능하게 변경)
  src/components/Tabs/SearchCategoryTab.tsx
Labels: a11y, styling

#302 인스턴트 검색 결과와 성인 제외 버튼사이 디바이더 추가
  src/components/Search/InstantSearch.tsx
  src/components/Search/InstantSearchResult.tsx
Labels: styling

#307 도서 상세 페이지에서 성인 제외 스위치가 깨지는 문제 수정
  src/components/Switch/Switch.tsx
Labels: styling

#306 active, focus, hover 등 style 추가
  src/components/Book/SearchLandscapeBook.tsx
  src/components/BookThumbnail/ThumbnailRenderer.tsx
  src/components/Search/FilterSelector.tsx
  src/components/Search/InstantSearchResult.tsx
Labels: styling

#301 앵커를 별도의 styled-components 로 변경
  src/components/Pagination/Pagination.tsx
Labels: ie11, styling

#309 카테고리 넘김 버튼 style 수정
  src/components/Pagination/Pagination.tsx
  src/components/Tabs/SearchCategoryTab.tsx
  src/svgs/ArrowBoldV.svg
Labels: styling

#311 active, hover 상태 추가 반영
  src/components/Pagination/Pagination.tsx
  src/components/Search/FilterSelector.tsx
  src/components/Search/InstantSearchResult.tsx
Labels: styling

#310 검색 결과 페이지에서 도서 클릭 트래킹 추가
  src/components/Book/SearchLandscapeBook.tsx
  src/pages/search/index.tsx
Labels: tracking

#312 인스턴트 서치 포커스 잃을 때 isAdultExclude 재설정 막음
  src/components/Search/InstantSearch.tsx
Labels: hotfix

#314 필요한 searchParam 만 필터에서 추가(is_login 제외)
  src/components/Search/AdultExcludeToggle.tsx
  src/components/Search/FilterSelector.tsx
Labels: hotfix

#317 useSearchQueries 훅 추가
  src/components/Pagination/Pagination.tsx
  src/components/Search/AdultExcludeToggle.tsx
  src/components/Search/FilterSelector.tsx
  src/components/Tabs/SearchCategoryTab.tsx
  src/hooks/useSearchQueries.ts
Labels: refactor

#321 검색 CSR 사용
  src/hooks/useSearchQueries.ts
  src/pages/search/index.tsx
  src/tests/pages/search/Index.spec.tsx
  src/utils/search.ts
Labels: enhancement, refactor

#322 디자인 QA 5
  src/components/Book/SearchLandscapeBook.tsx
  src/components/BookThumbnail/ThumbnailRenderer.tsx
  src/components/Pagination/Pagination.tsx
  src/components/Search/AdultExcludeToggle.tsx
  src/components/Tabs/SearchCategoryTab.tsx
  src/pages/search/index.tsx
Labels: styling

#323 장르 홈에서 불필요한 도서 DESC 받지 않도록 잠시 수정
  src/components/Section/AIRecommendationSection.tsx
  src/components/Section/UserPreferredSection.tsx
  src/pages/[genre]/index.tsx
  src/pages/search/index.tsx
  src/services/books/reducer.ts
  src/services/books/saga.ts
Labels: temporary

#325 카테고리 탭 스켈레톤 추가
  src/components/Book/SearchLandscapeBook.tsx
  src/components/Tabs/SearchCategoryTab.tsx
  src/pages/search/index.tsx
Labels: styling

#326 검색 스켈레톤 전체적으로 추가 (1)
  src/components/Search/Authors/AuthorInfo.tsx
  src/components/Search/Authors/index.tsx
  src/components/Search/InstantSearchResult.tsx
  src/components/Search/SearchLandscapeBook/MetaWrapper.ts
  src/components/Search/SearchLandscapeBook/PriceInfo.tsx
  src/components/Search/SearchLandscapeBook/index.tsx
  src/components/Skeleton/Bar.ts
  src/components/Skeleton/Book.ts
  src/components/Skeleton/CategoryTab.tsx
  src/components/Skeleton/SearchLandscapeBook.tsx
  src/pages/search/index.tsx
  src/tests/components/Book/PriceInfo.spec.tsx
Labels: refactor, styling

#332 AccountContext 작성
  src/components/BookThumbnail/ThumbnailRenderer.tsx
  src/components/GNB/index.tsx
  src/components/Section/AIRecommendationSection.tsx
  src/components/Section/UserPreferredSection.tsx
  src/hooks/useAccount.ts
  src/hooks/useEventTracker.tsx
  src/pages/[genre]/index.tsx
  src/pages/_app.tsx
  src/pages/notification/index.tsx
  src/pages/search/index.tsx
  src/services/accounts/index.ts
  src/services/accounts/reducer.ts
  src/services/accounts/request.ts
  src/services/accounts/saga.ts
  src/store/config.ts
  src/store/initialState.ts
  src/store/reducers.ts
  src/store/sagas.ts
  src/tests/__mocks__/mockModules.tsx
  src/tests/components/MultipleLineBook/MultipleLineBookComponent.spec.tsx
  src/tests/hooks/useAccount.spec.ts
  src/tests/pages/__App.spec.tsx
  src/tests/pages/notifications/NotificationPage.spec.tsx
  src/tests/pages/partials/gnb/Index.spec.tsx
  src/tests/pages/search/Index.spec.tsx
  src/utils/backoff.ts
Labels: enhancement

#334 App 테스트 재작성
  src/tests/pages/__App.spec.tsx
Labels: testing

#335 AccountContext test 수정
  src/tests/hooks/useAccount.spec.ts
Labels: testing
