Repository ridi/books-frontend, pull requests merged in 2020-02, with the labels that each got.

#6 Update docker-compose.*.yml files
  docker-compose.cypress.yml
  docker-compose.yml
  provisioning/e2e/Dockerfile
  provisioning/local/Dockerfile
  provisioning/local/run.sh
Labels: refactor

#7 Fix: lintstagedrc
  .circleci/config.yml
  .huskyrc.js
  .lintstagedrc
  package.json
Labels: chore

#15 TopBanner 흔들림 해결
  src/components/TopBanner/TopBannerCarousel.tsx
Labels: hotfix

#12 CSP 설정에 구글 font 경로 추가
  server/csp.js
Labels: chore, security

#16 Update mergify and circle-ci for branching strategy
  .circleci/config.yml
  .mergify.yml
Labels: chore

#13 authors_ordered -> authors 변경
  src/components/BookMeta/BookMeta.tsx
  src/components/RecommendedBook/RecommendedBook.tsx
  src/tests/components/Badge/BookBadgeRenderer.spec.tsx
  src/tests/components/BookSelections/SelectionBook.spec.tsx
  src/tests/utils/common.spec.ts
  src/types/book.ts
Labels: chore

#20 Fix: serverless deploy list command stage parameter
  .circleci/config.yml
Labels: hotfix

#18 flex-shrink: 0 적용하여 넓이가 안드 5.0.1 에서 자동으로 줄어드는 것 방지
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBook.tsx
  src/components/BookSections/SelectionBook/SelectionBookList.tsx
  src/components/BookThumbnail/ThumbnailRenderer.tsx
  src/components/GNB/index.tsx
  src/components/KeywordFinder/HomeKeywordFinderSection.tsx
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
  src/components/QuickMenu/QuickMenuList.tsx
  src/components/Search/InstantSearch.tsx
Labels: bug

#14 Replace store links to relative url
  .circleci/config.yml
  src/components/BookMeta/BookMeta.tsx
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBook.tsx
  src/components/GNB/index.tsx
  src/components/KeywordFinder/HomeKeywordFinderSection.tsx
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
  src/components/RecommendedBook/RecommendedBook.tsx
  src/components/RecommendedBook/RecommendedBookCarousel.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
  src/components/Search/InstantSearch.tsx
  src/components/Section/UserPreferredSection.tsx
Labels: refactor

#24 manifest 경로 cdn 으로 이동
  src/pages/Meta.tsx
Labels: chore

#22 `notify` job convert to after-scripts parameter
  .circleci/config.yml
Labels: chore

#23 development build environment fixed and `-s staging` reverted
  .circleci/config.yml
Labels: chore

#32 개발 서버 환경 변수 수정
  .circleci/config.yml
  env/publicRuntimeConfig.js
  package.json
  serverless.yml
  src/utils/axios.ts
  yarn.lock
Labels: chore

#36 Use `squash` when merge backport
  .mergify.yml
Labels: chore

#34 Fix: rollback job attach_workspace
  .circleci/config.yml
Labels: chore

#40 검색 input창 text 수직 정렬 style 수정
  src/components/Search/InstantSearch.tsx
Labels: styling

#10 프로덕션 배포 후 프로파일링을 하도록 함
  .circleci/config.yml
Labels: enhancement

#41 사용하지 않는 패키지 제거
  package.json
  serverless.yml
  yarn.lock
Labels: chore

#37 CSP 서드파티 벤더 따로 분리 및 오타 수정
  server/csp.js
Labels: chore, security

#47 Hotfix/Edge 에서는 URLSearchParam 객체를 생성자로 포함이 불가능 한 부분 수정
  package.json
  src/components/KeywordFinder/HomeKeywordFinderSection.tsx
  yarn.lock
Labels: hotfix

#49 lint-staged의 glob 식 수정
  .lintstagedrc
Labels: chore

#44 Fix: release notify message
  .circleci/config.yml
Labels: chore

#39 Rename docker-compose.override.yml to docker-compose.traefik.yml
  .gitignore
  docker-compose.traefik.yml
  package.json
Labels: chore

#45 Refactor/styled component - for Badges
  src/components/Badge/AdultBadge.tsx
  src/components/Badge/BookBadgeRenderer.tsx
  src/components/Badge/FreeBookRenderer.tsx
  src/components/Badge/SetBookRenderer.tsx
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBook.tsx
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
  src/components/RecommendedBook/RecommendedBookCarousel.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
  src/tests/components/Badge/BookBadgeRenderer.spec.tsx
Labels: refactor, styling

#52 알림 반응형 페이지 개발
  src/components/PageTitle/PageTitle.tsx
  src/components/Placeholder/NotificationItemPlaceholder.tsx
  src/components/Tabs/MainTab.tsx
  src/hooks/useEventTracker.tsx
  src/pages/_app.tsx
  src/pages/inapp/notification/index.tsx
  src/pages/notification/index.tsx
  src/services/notification/index.ts
  src/services/notification/reducer.ts
  src/services/notification/request.ts
  src/services/notification/saga.ts
  src/store/config.ts
  src/store/initialState.ts
  src/store/reducers.ts
  src/store/sagas.ts
  src/styles/themes.ts
  src/tests/components/Tabs/MainTab.spec.tsx
  src/tests/pages/notifications/NotificationPage.spec.tsx
  src/types/common.ts
  src/types/notification.ts
  src/utils/axiosInterceptors.ts
Labels: enhancement

#53 axios-logger 관련 모듈을 Next.js 에서 트랜스파일 못하는 부분을 수정합니다. (for IE11)
  next.config.js
  package.json
  src/utils/axios.ts
  yarn.lock
Labels: bug, ie11

#51 InstantSearch isPartial 제거 및 styled-component 적용
  src/components/GNB/index.tsx
  src/components/Search/InstantSearch.tsx
Labels: refactor

#57 스케줄 된 Google Lighthouse audit 추가
  .github/workflows/google-lighthouse.yml
Labels: testing

#54 Jest 테스팅과 Codecov 용 Github Actions 를 추가.
  .github/workflows/jest-codecov.yml
  README.md
  codecov.yml
  package.json
  src/tests/__mocks__/mockModules.tsx
  src/tests/components/Badge/BookBadgeRenderer.spec.tsx
  src/tests/components/Tabs/GenreTab.spec.tsx
  src/tests/components/Tabs/MainTab.spec.tsx
  src/tests/pages/Index.spec.tsx
  src/tests/pages/__App.spec.tsx
  src/tests/pages/partials/gnb/Index.spec.tsx
  src/tests/setup.js
  yarn.lock
Labels: testing

#58 퀵메뉴 섹션 필요 없는 Wrapper 삭제 및 스타일 정리
  src/components/QuickMenu/QuickMenuList.tsx
Labels: refactor, styling

#62 이벤트 배너 스타일 정리
  src/components/EventBanner/EventBanner.tsx
  src/components/EventBanner/EventBannerItem.tsx
  src/components/EventBanner/EventBannerList.tsx
Labels: refactor, styling

#63 반응형 썸네일 srcset 지정
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBook.tsx
  src/components/BookThumbnail/ThumbnailRenderer.tsx
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
  src/components/RecommendedBook/RecommendedBook.tsx
  src/components/RecommendedBook/RecommendedBookCarousel.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
Labels: enhancement, refactor
