Repository ridi/books-frontend, pull requests merged in 2020-04, with the labels that each got.

#179 Fix: rollback job
  .circleci/config.yml
  package.json
Labels: CI/CD, bug

#177 쿠키 회귀 테스트 추가
  src/components/Tabs/GenreTab.tsx
  src/tests/components/Tabs/GenreTab.spec.tsx
Labels: bug, testing

#180 Fix/instant search UI
  src/assets/svg/Author.svg
  src/components/Search/InstantSearch.tsx
  src/components/Search/InstantSearchResult.tsx
  src/constants/icons.ts
  src/tests/components/Search/InstantSearch.spec.tsx
  src/tests/components/Search/abc.fixture.json
Labels: styling

#184 인앱 알림 디자인 QA 반영
  src/components/Misc/InAppThemeProvider.tsx
  src/components/Placeholder/NotificationItemPlaceholder.tsx
  src/pages/notification/index.tsx
  src/styles/themes.ts
Labels: hotfix, styling

#186 디자인QA 반영
  src/components/Search/InstantSearchResult.tsx
  src/tests/components/Search/abc.fixture.json
Labels: styling

#187 _error.tsx 정리 (1)
  src/pages/[genre]/index.tsx
  src/pages/_error.tsx
Labels: refactor

#190 NotFoundError 추가
  src/pages/[genre]/index.tsx
  src/pages/_error.tsx
  src/utils/error.ts
Labels: chore, refactor

#191 Hotfix/_app 에서 테마 부를 때 req 없을 경우 처리
  src/pages/_app.tsx
Labels: hotfix

#194 store 팀 요청으로 master.test.ridi.io 를 dev.ridi.io 로 변경
  .env
Labels: support

#195 mediaQuery CSS가 문자열을 받아 문자열을 반환하도록 함
  src/components/Book/PortraitBook.tsx
  src/components/BookMeta/BookMeta.tsx
  src/components/BookSections/BookSectionContainer.tsx
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBook.tsx
  src/components/BookSections/SelectionBook/SelectionBookCarousel.tsx
  src/components/BookSections/SelectionBook/SelectionBookList.tsx
  src/components/Button/Button.tsx
  src/components/EventBanner/EventBanner.tsx
  src/components/EventBanner/EventBannerItem.tsx
  src/components/EventBanner/EventBannerList.tsx
  src/components/Footer/index.tsx
  src/components/GNB/index.tsx
  src/components/KeywordFinder/HomeKeywordFinderSection.tsx
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
  src/components/PageTitle/PageTitle.tsx
  src/components/Placeholder/NotificationItemPlaceholder.tsx
  src/components/QuickMenu/QuickMenuList.tsx
  src/components/RecommendedBook/RecommendedBookCarousel.tsx
  src/components/Search/InstantSearch.tsx
  src/components/Search/InstantSearchHistory.tsx
  src/components/Search/InstantSearchResult.tsx
  src/components/Tabs/GenreTab.tsx
  src/components/Tabs/MainTab.tsx
  src/pages/category/list/index.tsx
  src/pages/notification/index.tsx
  src/utils/mediaQuery.ts
Labels: enhancement, refactor

#188 통합 검색 결과 타입 추가
  src/pages/search/index.tsx
  src/pages/search/types.ts
  src/tests/pages/search/Index.spec.tsx
  src/tests/pages/search/searchResult.fixture.json
Labels: chore

#193 Hotfix/top banner carousel click event 추가
  src/components/TopBanner.tsx
Labels: hotfix, tracking

#199 search type 정의 pages 하위 말고 상위 types 디렉토리로 이동
  src/pages/search/index.tsx
  src/types/searchResults.ts
Labels: chore

#198 추가 디자인 QA 반영
  src/components/BookMeta/BookMeta.tsx
  src/components/Search/InstantSearchHistory.tsx
  src/components/Search/InstantSearchResult.tsx
Labels: styling

#200 혼자 떨어져나온 orBelow를 css``로 감쌈
  src/components/GNB/index.tsx
Labels: bug

#201 keyframes 를 css`` 사이에 놓도록 수정
  src/components/Search/InstantSearch.tsx
Labels: styling

#204 MultipleLineBooks 여백 수정
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
Labels: bug, styling

#189 LHCI uses-passive-event-listeners 오류로 잡던 걸 warn 으로 변경
  README.md
  lighthouserc.json
Labels: testing

#205 hotfix/소설 태그 올바르게 나오도록 수정
  src/components/BookMeta/index.tsx
Labels: hotfix

#208 webfontloader 사용해 Windows에서만 나눔고딕 로드
  package.json
  src/components/Meta/index.tsx
  src/pages/_app.tsx
  src/styles/reset.ts
  yarn.lock
Labels: enhancement, refactor

#202 SelectionBook 리팩토링 (1)
  src/components/Badge/BookBadgeRenderer.tsx
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBook.tsx
  src/components/BookSections/SelectionBook/SelectionBookCarousel.tsx
  src/components/BookSections/SelectionBook/SelectionBookItem.tsx
  src/components/BookSections/SelectionBook/SelectionBookList.tsx
  src/components/BookSections/SelectionBook/types.ts
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
  src/components/RecommendedBook/RecommendedBookItem.tsx
  src/components/Section/AIRecommendationSection.tsx
  src/components/Section/HomeSectionRenderer.tsx
  src/components/Section/UserPreferredSection.tsx
  src/hooks/useExcludeRecommedation.ts
  src/tests/components/BookSelections/SelectionBook.spec.tsx
  src/utils/recommendation.ts
Labels: enhancement, refactor

#209 lighthouserc 오타를 수정합니다.
  lighthouserc.json
Labels: typo

#207 partials에서 sentry 초기화 안 함
  src/pages/_document.tsx
  src/utils/sentry.ts
Labels: chore

#203 통합 검색 페이지에 저자 목록 표시
  package.json
  src/components/Search/InstantSearch.tsx
  src/components/Search/InstantSearchResult.tsx
  src/pages/search/index.tsx
  src/svgs/ArrowBoldH.svg
  src/tests/pages/search/Index.spec.tsx
  src/types/searchResults.ts
  yarn.lock
Labels: refactor, styling

#211 Update darkTheme placeholder colors
  src/styles/themes.ts
Labels: styling

#213 name 이 없는 경우가 있어 optional chaining 추가
  src/pages/_app.tsx
Labels: testing

#214 Remove NotificationPlaceholderWrap border opacity
  src/components/Placeholder/NotificationItemPlaceholder.tsx
Labels: styling

#215 Hotfix/section 이름 앞에 deviceType 붙임
  src/components/TopBanner.tsx
Labels: bug, hotfix, tracking

#212 SelectionBook 리팩토링 (2)
  src/components/Book/PortraitBook.tsx
  src/components/BookSections/SelectionBook/SelectionBookCarousel.tsx
  src/components/BookSections/SelectionBook/SelectionBookItem.tsx
  src/components/BookSections/SelectionBook/SelectionBookList.tsx
  src/components/RecommendedBook/RecommendedBookItem.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
Labels: enhancement, refactor

#220 Fix: c3703e5da767449bfb8749ccaba537b7e4abe21a
  .circleci/config.yml
Labels: CI/CD

#222 몇 가지 버그 수정
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/styles/reset.ts
  src/types/global.d.ts
  src/utils/sentry.ts
Labels: bug, hotfix

#224 스크롤 컨테이너에 불필요한 수직 스크롤이 나타나는 걸 막습니다.
  src/components/ScrollContainer.tsx
Labels: hotfix, styling

#221 dangerouslySetInnerHTML 수 줄임
  src/components/BookMeta/BookMeta.tsx
  src/components/BookThumbnail/ThumbnailRenderer.tsx
  src/components/Search/InstantSearchResult.tsx
  src/tests/utils/__snapshots__/highlight.spec.ts.snap
  src/tests/utils/highlight.spec.ts
  src/utils/bookTitleGenerator.ts
  src/utils/highlight.ts
Labels: enhancement, refactor

#228 패키지 업데이트
  package.json
  yarn.lock
Labels: chore

#230 Fix: /inapp/notification PageTitle on tablet
  src/pages/notification/index.tsx
Labels: hotfix

#234 Fix: hotfix notify
  .circleci/config.yml
Labels: chore

#237 BookMeta에서 showRating의 기능을 ratingInfo와 합침
  src/components/BookMeta/index.tsx
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBookItem.tsx
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
Labels: refactor

#233 SelectionBookList 리팩토링
  src/components/BookSections/SelectionBook/SelectionBookList.tsx
Labels: enhancement, refactor

#239 SelectionBook 리팩토링 (n)
  src/components/BookSections/BookSectionContainer.tsx
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SectionTitle.tsx
  src/components/BookSections/SelectionBook/index.tsx
  src/components/Section/AIRecommendationSection.tsx
  src/components/Section/HomeSectionRenderer.tsx
  src/components/Section/UserPreferredSection.tsx
Labels: refactor

#219 Chore/TypeScript strict true
  package.json
  src/components/Book/PortraitBook.tsx
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookThumbnail/ThumbnailRenderer.tsx
  src/components/Button/Button.tsx
  src/components/Carousel/Arrow.tsx
  src/components/CategoryList/Desktop.tsx
  src/components/CategoryList/Mobile.tsx
  src/components/GNB/HomeLink.tsx
  src/components/GNB/index.tsx
  src/components/Misc/Anchor.tsx
  src/components/Misc/index.ts
  src/components/QuickMenu/QuickMenuList.tsx
  src/components/RecommendedBook/BookMeta.tsx
  src/components/RecommendedBook/RecommendedBookItem.tsx
  src/components/ScrollContainer.tsx
  src/components/Search/InstantSearch.tsx
  src/components/Search/InstantSearchHistory.tsx
  src/components/Search/InstantSearchResult.tsx
  src/components/Section/AIRecommendationSection.tsx
  src/components/Section/HomeSectionRenderer.tsx
  src/components/Section/UserPreferredSection.tsx
  src/components/StarRating/StarRating.tsx
  src/components/Tabs/GenreTab.tsx
  src/components/TopBanner.tsx
  src/hooks/useCartCount.tsx
  src/hooks/useDeviceType.tsx
  src/hooks/useEventTracker.tsx
  src/hooks/useIntersectionObserver.ts
  src/hooks/useScrollPosition.ts
  src/hooks/useScrollSlider.ts
  src/hooks/useViewportIntersection.tsx
  src/pages/[genre]/index.tsx
  src/pages/_app.tsx
  src/pages/_error.tsx
  src/pages/api/manifest.webmanifest.tsx
  src/pages/category/list/index.tsx
  src/pages/notification/index.tsx
  src/pages/partials/gnb/index.tsx
  src/pages/search/index.tsx
  src/services/accounts/reducer.ts
  src/services/books/reducer.ts
  src/services/books/saga.ts
  src/services/notification/reducer.ts
  src/services/notification/saga.ts
  src/styles/themes.ts
  src/types/book.ts
  src/types/sections.ts
  src/utils/axios.ts
  src/utils/axiosInterceptors.ts
  src/utils/bookTitleGenerator.ts
  src/utils/common.ts
  src/utils/highlight.ts
  src/utils/retry.ts
  src/utils/scrollTo.ts
  src/utils/sentry.ts
  src/utils/titleGenerator.ts
  tsconfig.json
  yarn.lock
Labels: chore

#236 ThumbnailRenderer 에 도서 상세를 주입하지 않고 필요한 정보(isAdultOnly, bId, title) 만 주입
  src/components/Book/PortraitBook.tsx
  src/components/BookMeta/BookMeta.tsx
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBookItem.tsx
  src/components/BookThumbnail/ThumbnailRenderer.tsx
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
  src/components/RecommendedBook/RecommendedBookItem.tsx
  src/pages/search/index.tsx
  src/tests/pages/search/Index.spec.tsx
  src/types/book.ts
  src/utils/bookTitleGenerator.ts
  src/utils/books.ts
Labels: refactor

#244 잘못된 파라미터 수정
  src/components/BookSections/SelectionBook/SelectionBookItem.tsx
Labels: bug

#247 푸터 콘텐츠 제공 문의 링크 변경
  src/components/Footer/index.tsx
Labels: hotfix, support

#245 RankingBook 리팩토링 (1)
  src/components/Book/PortraitBook.tsx
  src/components/Book/ThumbnailWithBadge.tsx
  src/components/BookSections/RankingBook/RankingBookList.tsx
Labels: refactor

#216 검색 페이지 카테고리 탭
  src/components/ScrollContainer.tsx
  src/components/Tabs/SearchCategoryTab.tsx
  src/components/Tabs/index.ts
  src/pages/search/index.tsx
  src/svgs/ArrowBoldV.svg
  src/tests/pages/search/Index.spec.tsx
Labels: feature, styling

#246 Runtypes 적용
  package.json
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBookItem.tsx
  src/components/BookSections/SelectionBook/index.tsx
  src/components/BookSections/SelectionBook/types.ts
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
  src/components/RecommendedBook/RecommendedBookCarousel.tsx
  src/components/RecommendedBook/RecommendedBookItem.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
  src/components/RecommendedBook/types.ts
  src/components/Section/AIRecommendationSection.tsx
  src/components/Section/HomeSectionRenderer.tsx
  src/components/Section/UserPreferredSection.tsx
  src/components/TopBanner.tsx
  src/pages/[genre]/index.tsx
  src/tests/components/Badge/BookBadgeRenderer.spec.tsx
  src/tests/components/BookSelections/SelectionBook.spec.tsx
  src/tests/components/RecommendedBook/RecommendedBook.spec.tsx
  src/types/sections.ts
  yarn.lock
Labels: refactor
