Repository ridi/books-frontend, pull requests merged in 2020-07, with the labels that each got.

#397 hotfix/input 에 aria-label 추가
  src/assets/svg/Lens.svg
  src/components/Search/InstantSearch/index.tsx
  src/constants/icons.ts
  src/tests/pages/partials/gnb/Index.spec.tsx
Labels: a11y, hotfix

#398 Hotfix/Reset focusedPosition
  src/components/Search/InstantSearch/index.tsx
Labels: hotfix

#399 Add prefix for webtoon section
  src/components/BookSections/SelectionBook/index.tsx
Labels: support, temporary

#414 Fix: NotificationItem component use landingUrl prop
  src/pages/notification/index.tsx
Labels: hotfix

#420 잘못된 deeplinkUrl 로 이동하지 않도록 하기 위한 임시 코드
  src/pages/notification/index.tsx
Labels: temporary

#408 필요없는 lint rule 삭제 및 workbox 제거
  .eslintrc.js
  next.config.js
  package.json
  src/components/Badge/FreeBookRenderer.tsx
  src/components/Book/ThumbnailWithBadge.tsx
  src/components/BookMeta/BookMeta.tsx
  src/components/BookMeta/index.tsx
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SectionTitle.tsx
  src/components/BookSections/SelectionBook/SelectionBookCarousel.tsx
  src/components/BookSections/SelectionBook/SelectionBookItem.tsx
  src/components/Button/Button.tsx
  src/components/Carousel/Arrow.tsx
  src/components/Carousel/BooksCarousel.tsx
  src/components/CategoryList/Desktop.tsx
  src/components/CategoryList/Mobile.tsx
  src/components/EventBanner/EventBanner.tsx
  src/components/EventBanner/EventBannerList.tsx
  src/components/GNB/HomeLink.tsx
  src/components/GNB/index.tsx
  src/components/Meta/CSP.tsx
  src/components/Meta/Favicon.tsx
  src/components/Meta/index.tsx
  src/components/Misc/PartialSeparator.tsx
  src/components/PageTitle/PageTitle.tsx
  src/components/Placeholder/NotificationItemPlaceholder.tsx
  src/components/QuickMenu/QuickMenuList.tsx
  src/components/RecommendedBook/RecommendedBookCarousel.tsx
  src/components/RecommendedBook/index.tsx
  src/components/Search/InstantSearch/Result.tsx
  src/components/Search/SearchLandscapeBook/PriceInfo.tsx
  src/components/Search/SearchLandscapeBook/index.tsx
  src/components/Skeleton/CategoryTab.tsx
  src/components/Skeleton/SearchLandscapeBook.tsx
  src/components/Switch/index.tsx
  src/components/Tabs/GenreTab.tsx
  src/components/Tabs/MainTab.tsx
  src/components/Tag/Tag.tsx
  src/hooks/useAccount.ts
  src/hooks/useNotification.ts
  src/pages/[genre]/index.tsx
  src/pages/_app.tsx
  src/pages/account/myridi/index.tsx
  src/pages/cart/index.tsx
  src/pages/category/list/index.tsx
  src/pages/notification/index.tsx
  src/pages/partials/footer/index.tsx
  src/pages/partials/gnb/index.tsx
  src/service-worker.js
  src/tests/components/CategoryList/CategoryList.spec.tsx
  src/tests/utils/MockIO.ts
  src/utils/scrollTo.ts
  src/utils/sentry.ts
  tsconfig.json
  yarn.lock
Labels: refactor

#421 이 책 어때요 섹션 우측 패딩 조정
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
Labels: bug, hotfix, styling

#431 Fix: window.isExternalLink
  src/pages/inapp/search.tsx
Labels: hotfix

#434 Split NotificationItem component file
  src/components/Notification/NotificationItem.tsx
  src/components/Notification/NotificationItemPlaceholder.tsx
  src/pages/notification/index.tsx
Labels: refactor
