Repository ridi/books-frontend, pull requests merged in 2020-06, with the labels that each got.

#338 pages/[genre] 테스트 수정
  src/tests/pages/GenreHome.spec.tsx
Labels: testing

#339 hotfix/update-event-tracker
  package.json
  yarn.lock
Labels: hotfix, tracking

#241 새 AI 추천 API 적용
  .env
  .env.production
  src/components/BookMeta/BookMeta.tsx
  src/components/GNB/HomeLink.tsx
  src/components/Section/AIRecommendationSection.tsx
  src/components/Section/HomeSectionRenderer.tsx
  src/components/Tabs/GenreTab.tsx
  src/types/sections.ts
  src/utils/common.ts
Labels: enhancement

#344 AIRecommendationBook 타입 사용처 제거
  src/components/BookSections/SelectionBook/SelectionBookCarousel.tsx
  src/components/BookSections/SelectionBook/SelectionBookItem.tsx
  src/components/BookSections/SelectionBook/types.ts
Labels: refactor

#345 ThumbnailWithBadge 테스트 추가
  src/tests/components/Book/ThumbnailWithBadge.spec.tsx
  src/tests/components/Book/books.fixture.json
Labels: testing

#346 hotfix/추천 영역 센트리 불필요한 알림 발송 수정
  src/components/Section/AIRecommendationSection.tsx
Labels: hotfix

#350 book-api 응답 전처리
  src/components/Book/ThumbnailWithBadge.tsx
  src/components/BookMeta/BookMeta.tsx
  src/components/BookMeta/index.tsx
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
  src/components/Search/SearchLandscapeBook/PriceInfo.tsx
  src/components/Search/SearchLandscapeBook/index.tsx
  src/services/books/reducer.ts
  src/services/books/saga.ts
  src/tests/components/Badge/BookBadgeRenderer.spec.tsx
  src/tests/components/Book/PriceInfo.spec.tsx
  src/tests/components/Book/ThumbnailWithBadge.spec.tsx
  src/tests/components/Book/fixtures/free-book.fixture.json
  src/tests/components/Book/fixtures/price-zero.fixture.json
  src/tests/components/Book/fixtures/search-api-price-exist.fixture.json
  src/tests/components/Book/fixtures/simple-books.fixture.json
  src/tests/components/Book/fixtures/trial-book.fixture.json
  src/tests/components/BookSelections/RankingBookList.spec.tsx
  src/tests/components/BookSelections/SelectionBook.spec.tsx
  src/tests/components/MultipleLineBook/MultipleLineBookComponent.spec.tsx
  src/tests/components/RecommendedBook/RecommendedBook.spec.tsx
  src/tests/types/__snapshots__/book.spec.ts.snap
  src/tests/types/book.spec.ts
  src/tests/types/books.fixture.json
  src/tests/utils/common.spec.ts
  src/types/book.ts
  src/utils/bookTitleGenerator.ts
  src/utils/books.ts
  src/utils/common.ts
Labels: enhancement

#266 search 페이지 LHCI 추가 및 assertion 옵션 수정
  lighthouserc.json
Labels: testing

#351 책 가격 정보 정리
  src/components/Book/ThumbnailWithBadge.tsx
  src/tests/components/Book/fixtures/price-zero.fixture.json
  src/tests/components/Book/fixtures/search-api-price-exist.fixture.json
  src/tests/components/Book/fixtures/simple-books.fixture.json
  src/tests/components/Book/fixtures/trial-book.fixture.json
  src/tests/types/__snapshots__/book.spec.ts.snap
  src/types/book.ts
Labels: enhancement

#352 serverless.yml 메모리, 타임아웃 설정을 수정합니다.
  serverless.yml
Labels: chore

#354 wrapCatchCancel 버그 수정
  src/components/GNB/index.tsx
  src/utils/axios.ts
Labels: bug

#353 _app과 _document 정리
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/tests/pages/__App.spec.tsx
Labels: refactor

#356 모든 환경에 AccountProvider 추가
  src/pages/_app.tsx
Labels: hotfix

#355 이벤트 트래커 유틸리티 개선
  src/components/BookSections/SelectionBook/SelectionBookItem.tsx
  src/components/BookThumbnail/ThumbnailRenderer.tsx
  src/components/EventBanner/EventBannerList.tsx
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
  src/components/QuickMenu/QuickMenuList.tsx
  src/components/Search/SearchLandscapeBook/index.tsx
  src/components/TopBanner.tsx
  src/hooks/useAccount.ts
  src/pages/[genre]/index.tsx
  src/pages/notification/index.tsx
  src/pages/search/index.tsx
  src/utils/event-tracker.ts
Labels: enhancement, refactor

#361 NotFoundError 체크 수정, 센트리 옵션 수정
  package.json
  src/pages/_error.tsx
  src/utils/error.ts
  src/utils/sentry.ts
  yarn.lock
Labels: chore

#363 에러 페이지 `자세히 보기` 수정
  src/pages/_error.tsx
Labels: hotfix

#366 로컬스토리지 fallback 추가
  src/components/Misc/DisallowedHostsFilter.tsx
  src/components/Search/InstantSearch.tsx
  src/components/Tabs/GenreTab.tsx
  src/utils/event-tracker.ts
  src/utils/storages.ts
Labels: hotfix

#367 검색 스켈레톤 왼쪽 마진 조정
  src/components/Skeleton/AuthorInfo.tsx
  src/components/Skeleton/CategoryTab.tsx
  src/pages/search/index.tsx
Labels: styling

#365 집 앞 신간 WCAG 반영
  src/components/BookMeta/BookMeta.tsx
  src/components/RecommendedBook/BookMeta.tsx
  src/components/RecommendedBook/RecommendedBookItem.tsx
Labels: a11y

#371 LHCI audit 오류 수정(search page)
  src/components/Search/FilterSelector.tsx
Labels: a11y

#375 next-redux-wrapper 업데이트
  package.json
  src/pages/[genre]/index.tsx
  src/pages/_app.tsx
  src/services/books/reducer.ts
  src/services/category/reducer.ts
  src/store/config.ts
  src/tests/components/BookSelections/RankingBookList.spec.tsx
  src/tests/components/BookSelections/SelectionBook.spec.tsx
  src/tests/components/EventBanner/EventBanner.spec.tsx
  src/tests/components/MultipleLineBook/MultipleLineBookComponent.spec.tsx
  src/tests/components/QuickMenu/QuickMenuList.spec.tsx
  src/tests/components/RecommendedBook/RecommendedBook.spec.tsx
  src/tests/components/Tabs/MainTab.spec.tsx
  src/tests/components/TopBanner.spec.tsx
  src/tests/pages/__App.spec.tsx
  src/tests/pages/partials/footer/Index.spec.tsx
  src/tests/pages/partials/gnb/Index.spec.tsx
  src/tests/utils/makeStore.ts
  src/types/common.ts
  src/utils/sentry.ts
  yarn.lock
Labels: enhancement

#378 Fix: call setUserId before send pageview event
  src/hooks/useAccount.ts
Labels: hotfix

#381 redux 스토어에서 사용되지 않는 isFetching 제거
  src/services/books/reducer.ts
  src/services/books/saga.ts
  src/services/category/reducer.ts
  src/services/category/saga.ts
  src/store/initialState.ts
  src/tests/components/BookSelections/RankingBookList.spec.tsx
  src/tests/components/BookSelections/SelectionBook.spec.tsx
  src/tests/components/EventBanner/EventBanner.spec.tsx
  src/tests/components/MultipleLineBook/MultipleLineBookComponent.spec.tsx
  src/tests/components/QuickMenu/QuickMenuList.spec.tsx
  src/tests/components/RecommendedBook/RecommendedBook.spec.tsx
Labels: refactor

#384 히스토리 아이템 패딩 조정, outline 삭제, 삭제 버튼 크기 고정
  src/components/Search/InstantSearchHistory.tsx
Labels: styling

#383 clientBookFields 제거
  src/components/RecommendedBook/BookMeta.tsx
  src/components/Search/SearchLandscapeBook/PriceInfo.tsx
  src/components/Search/SearchLandscapeBook/index.tsx
  src/hooks/useBookDetailSelector.ts
  src/services/books/reducer.ts
  src/services/books/saga.ts
  src/store/initialState.ts
  src/tests/components/Book/PriceInfo.spec.tsx
  src/tests/components/MultipleLineBook/MultipleLineBookComponent.spec.tsx
  src/tests/components/RecommendedBook/RecommendedBook.spec.tsx
  src/tests/types/books.fixture.json
  src/types/book.ts
  src/utils/common.ts
Labels: refactor

#385 InstantSearch 최소한의 스타일시트 정리
  src/components/Search/InstantSearch.tsx
  src/components/Search/InstantSearchHistory.tsx
  src/components/Search/InstantSearchResult.tsx
Labels: refactor, styling

#388 setUnreadCount(0) after requestFetchNotifications
  src/hooks/useNotification.ts
Labels: hotfix

#386 InstantSearch 재작성
  package.json
  src/components/GNB/index.tsx
  src/components/Search/InstantSearch.tsx
  src/components/Search/InstantSearch/History.tsx
  src/components/Search/InstantSearch/Result.tsx
  src/components/Search/InstantSearch/index.tsx
  src/components/Switch/index.tsx
  src/tests/components/Search/InstantSearch.spec.tsx
  src/tests/components/Search/abc.fixture.json
  src/tests/components/Search/instantSearch.fixture.json
  src/tests/utils/handle.spec.ts
  src/tests/utils/hangul.spec.ts
  src/utils/axios.ts
  src/utils/hangle.ts
  src/utils/hangul.ts
  src/utils/search.ts
  yarn.lock
Labels: enhancement, refactor

#392 ArrowLeft 추가, history 출력 5개로 제한
  src/components/Search/InstantSearch/index.tsx
Labels: styling

#393 GNB 레이아웃 수정
  src/components/Button/Button.tsx
  src/components/GNB/index.tsx
Labels: styling

#395 Fix: GNB notification tab add-on badge
  src/components/Tabs/MainTab.tsx
  src/hooks/useNotification.ts
Labels: hotfix
