Repository ridi/books-frontend, pull requests merged in 2020-03, with the labels that each got.

#64 메인탭 styled-component 적용
  src/components/Tabs/MainTab.tsx
Labels: refactor, styling

#56 Notification inapp webpack build
  .gitignore
  package.json
  src/components/InApp/InAppNotification.tsx
  src/inapp/index.html
  src/inapp/index.tsx
  src/pages/notification/index.tsx
  src/tests/pages/notifications/NotificationPage.spec.tsx
  webpack.config.js
  yarn.lock
Labels: enhancement

#66 Refactor/keyword finder section style
  src/components/KeywordFinder/HomeKeywordFinderSection.tsx
  src/tests/components/KeywordFinder/HomeKeywordFinderSection.spec.tsx
Labels: styling, testing

#68 hotfix/디스카운트 계산할 때 max 값은(100) 제외
  src/utils/common.ts
Labels: hotfix

#69 useViewportIntersection 추가
  src/hooks/useViewportIntersection.tsx
  src/pages/_app.tsx
  src/tests/hooks/useViewportIntersection.spec.tsx
Labels: enhancement, refactor

#75 ThumbnailRenderer에 useViewportIntersection 적용
  src/components/BookSections/SelectionBook/SelectionBook.tsx
  src/components/BookSections/SelectionBook/SelectionBookCarousel.tsx
  src/components/BookSections/SelectionBook/SelectionBookList.tsx
  src/components/BookThumbnail/ThumbnailRenderer.tsx
  src/components/RecommendedBook/RecommendedBook.tsx
  src/components/RecommendedBook/RecommendedBookCarousel.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
Labels: enhancement, refactor

#79 circle ci cache key 변경
  .circleci/config.yml
  README.md
Labels: chore

#61 lighthouse github actions plugin 사용하지 않고 직접 lighthouse-ci 호출사용으로 변경
  .github/workflows/google-lighthouse.yml
  lighthouserc.json
Labels: testing

#80 package install 커맨드 임시 변경
  .circleci/config.yml
  package.json
  yarn.lock
Labels: chore

#81 배포 관련 패키지 임시 추가
  .circleci/config.yml
Labels: chore

#76 useMultipleIntersectionObserver 최대한 제거
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBook.tsx
  src/components/BookSections/SelectionBook/SelectionBookCarousel.tsx
  src/components/BookSections/SelectionBook/SelectionBookList.tsx
  src/components/BookThumbnail/ThumbnailRenderer.tsx
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
  src/components/RecommendedBook/RecommendedBookCarousel.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
  src/hooks/useEventTracker.tsx
  src/tests/__mocks__/mockModules.tsx
  src/tests/components/BookSelections/SelectionBook.spec.tsx
  src/tests/components/RecommendedBook/RecommendedBook.spec.tsx
Labels: refactor, testing

#74 Refactor/인스턴트 검색 결과 및 히스토리 style 정리
  src/components/Search/InstantSearchHistory.tsx
  src/components/Search/InstantSearchResult.tsx
Labels: refactor, styling

#78 hotfix: RankingBookList 에서는 태그를 늘 표시하지 않음.
  src/components/BookSections/RankingBook/RankingBookList.tsx
Labels: hotfix, styling

#83 Restore .circleci/config.yml
  .circleci/config.yml
Labels: chore

#59 디자인QA 반영 / Notification Page Styled-component 적용
  src/components/PageTitle/PageTitle.tsx
  src/components/Placeholder/NotificationItemPlaceholder.tsx
  src/pages/notification/index.tsx
  static/svg/ChevronRight.svg
  static/svg/Notification_solid.svg
Labels: refactor, styling

#85 SelectionBookList 가 스크롤링 됐을 때 BookMeta가 제대로 표시 되지 않는 부분 수정
  src/components/BookSections/SelectionBook/SelectionBookList.tsx
  src/tests/components/BookSelections/SelectionBook.spec.tsx
Labels: bug, styling

#84 Feature/notification viewport intersection
  src/hooks/useEventTracker.tsx
  src/hooks/useMultipleIntersectionObserver.ts
  src/pages/notification/index.tsx
Labels: refactor

#87 빌드 시 ASSET_PREFIX 설정
  .circleci/config.yml
Labels: bug, chore

#86 MultipleLineBookComponent List 스타일 리팩토링 및
  src/components/Badge/BadgeContainer.tsx
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBook.tsx
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
  src/components/RecommendedBook/RecommendedBookCarousel.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
  src/tests/components/MultipleLineBook/MultipleLineBookComponent.spec.tsx
Labels: refactor, styling

#88 개발 환경에서 CSP 설정 수정, report-uri 주석 처리
  src/components/Meta/CSP.tsx
  src/tests/components/Meta/Meta.spec.tsx
Labels: chore, security

#46 탑 배너 캐러셀 개선
  package.json
  src/assets/image/expired_soon.png
  src/assets/image/expired_today.png
  src/components/Carousel/Arrow.tsx
  src/components/Carousel/BigBannerCarousel.spec.tsx
  src/components/Carousel/BigBannerCarousel.tsx
  src/components/Section/HomeSectionRenderer.tsx
  src/components/TopBanner.tsx
  src/components/TopBanner/TopBannerCarousel.tsx
  src/components/TopBanner/index.ts
  yarn.lock
Labels: enhancement

#94 libreact 대신 react-responsive 사용
  package.json
  src/components/BookSections/SelectionBook/SelectionBook.tsx
  src/components/RecommendedBook/RecommendedBook.tsx
  src/components/Search/InstantSearchResult.tsx
  src/hooks/useIsTablet.ts
  src/pages/category/list/index.tsx
  yarn.lock
Labels: enhancement

#95 라이트 하우스 CI 를 CircleCI Schedule job 으로 변경
  .circleci/config.yml
Labels: testing

#98 장르탭 하이라이팅 표시 버그 수정
  src/components/Tabs/GenreTab.tsx
Labels: bug, styling

#100 Remove trailing slashes in koa server
  next.config.js
  server.js
Labels: chore

#102 Fix: general genre home redirect
  server.js
Labels: bug

#104 Notification design qa
  src/components/Placeholder/NotificationItemPlaceholder.tsx
  src/pages/notification/index.tsx
Labels: styling

#101 Inapp into next pages
  inapp/Notification.tsx
  inapp/index.html
  inapp/index.tsx
  inapp/webpack.config.js
  package.json
  src/components/Misc/InAppThemeProvider.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/inapp/notification.tsx
  src/pages/notification/index.tsx
  yarn.lock
Labels: chore

#105 LH audit 에 일반장르 제외 bl, bl 연재 추가
  lighthouserc.json
Labels: testing

#103 Update GenreTab component
  src/components/Tabs/GenreTab.tsx
  src/components/Tabs/MainTab.tsx
Labels: refactor

#109 codecov threshold 조정
  codecov.yml
Labels: chore, testing

#107 TopBanner 동적 스타일링 양 줄임
  src/components/Carousel/BigBannerCarousel.spec.tsx
  src/components/Carousel/BigBannerCarousel.tsx
  src/components/TopBanner.tsx
Labels: refactor, styling

#99 책 목록 캐러셀 재작성
  package.json
  src/components/Book/PortraitBook.tsx
  src/components/BookMeta/BookMeta.tsx
  src/components/BookSections/BookSectionContainer.tsx
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBook.tsx
  src/components/BookSections/SelectionBook/SelectionBookCarousel.tsx
  src/components/BookSections/SelectionBook/SelectionBookList.tsx
  src/components/BookThumbnail/ThumbnailWrapper.tsx
  src/components/Carousel/BooksCarousel.tsx
  src/components/Carousel/CarouselWrapper.tsx
  src/components/Carousel/LoadableCarousel.tsx
  src/components/MultipleLineBooks/MultipleLineBooks.tsx
  src/components/RecommendedBook/RecommendedBook.tsx
  src/components/RecommendedBook/RecommendedBookCarousel.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
  src/pages/_app.tsx
  yarn.lock
Labels: enhancement

#112 Hotfix/add event tracker for quickmenu
  src/components/EventBanner/EventBannerList.tsx
  src/components/QuickMenu/QuickMenuList.tsx
  src/components/TopBanner.tsx
  src/constants/eventTracking.ts
  src/hooks/useEventTracker.tsx
  src/tests/components/QuickMenu/QuickMenuList.spec.tsx
Labels: hotfix

#111 GenreTab Style 정리
  src/components/Tabs/GenreTab.tsx
Labels: refactor, styling

#113 TopBanner 흔들림 현상 수정
  src/components/Carousel/BigBannerCarousel.spec.tsx
  src/components/Carousel/BigBannerCarousel.tsx
  src/components/TopBanner.tsx
Labels: styling

#110 Cypress E2E 테스팅 추가
  .eslintrc.js
  .github/workflows/cypress-e2e.yaml
  .github/workflows/google-lighthouse.yml
  README.md
  cypress.json
  cypress/cypress.webpack.config.js
  cypress/integration/01.partials_footer_spec.js
  cypress/integration/02.partials_gnb_spec.js
  cypress/integration/home_spec.ts
  cypress/plugins/index.js
  cypress/support/commands.ts
  cypress/support/defaults.ts
  cypress/support/index.d.ts
  cypress/support/index.ts
  cypress/tsconfig.json
  jest.config.js
  package.json
  yarn.lock
Labels: testing

#116 Use context for gnb link's origin url from querystring
  src/components/GNB/index.tsx
  src/components/Search/InstantSearch.tsx
  src/components/Tabs/MainTab.tsx
Labels: chore, enhancement

#118 탑 배너 첫 렌더 시 여백 적용 안 되는 문제 수정
  src/components/Carousel/BigBannerCarousel.tsx
Labels: styling

#119 circle ci 에서 lhci 스케줄 잡 삭제
  .circleci/config.yml
Labels: chore

#108 장르 홈에서 SPA로 페이징 시 전환 속도 향상
  src/components/GNB/index.tsx
  src/components/KeywordFinder/HomeKeywordFinderSection.tsx
  src/components/Section/AIRecommendationSection.tsx
  src/components/Tabs/GenreTab.tsx
  src/hooks/useCartCount.tsx
  src/pages/[genre]/index.tsx
  src/tests/pages/[genre].spec.tsx
  src/utils/axios.ts
  src/utils/dateTime.ts
Labels: enhancement, refactor

#97 Refactor/device type context
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBookList.tsx
  src/components/Context/DeviceType.tsx
  src/components/EventBanner/EventBannerList.tsx
  src/components/KeywordFinder/HomeKeywordFinderSection.tsx
  src/components/QuickMenu/QuickMenuList.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
  src/components/TopBanner.tsx
  src/hooks/useDeviceType.tsx
  src/hooks/useEventTracker.tsx
  src/pages/[genre]/index.tsx
  src/tests/components/TopBanner.spec.tsx
  src/tests/hooks/useDeviceType.spec.tsx
  src/utils/common.ts
Labels: refactor

#121 책 목록 스타일 땜빵
  src/components/RecommendedBook/RecommendedBook.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
  src/components/Section/HomeSectionRenderer.tsx
Labels: styling, temporary

#124 인스턴트 검색 결과 구분선 안나오는 문제 수정
  src/components/Search/InstantSearchResult.tsx
Labels: bug, styling

#123 데스크탑에서 책 목록 첫 렌더가 화면 너비 전체를 차지하던 문제 수정
  src/components/RecommendedBook/RecommendedBook.tsx
  src/components/RecommendedBook/RecommendedBookCarousel.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
Labels: bug, styling

#125 셀렉트 도서를 확인하지 못하는 문제 수정
  src/pages/[genre]/index.tsx
Labels: bug

#127 안 보이는 탑배너를 클릭 가능한 현상 수정
  src/components/TopBanner.tsx
Labels: styling

#122 장르 홈 WGAC 권고안 대비 변경
  src/components/Badge/BookBadgeRenderer.tsx
  src/components/BookMeta/BookMeta.tsx
  src/components/RecommendedBook/RecommendedBook.tsx
  src/components/Search/InstantSearchResult.tsx
  src/components/Tabs/GenreTab.tsx
Labels: a11y, styling

#129 Set event-tacker debug option from localstorage
  src/hooks/useEventTracker.tsx
Labels: chore

#130 Hotfix/@ridi/event-tracker 업데이트 요청
  package.json
  yarn.lock
Labels: hotfix, tracking

#133 Added approval job before production deploy job
  .circleci/config.yml
Labels: chore

#134 `NEXT_PUBLIC_` -> `NEXT_STATIC_`
  .env
  .env.production
  src/components/GNB/index.tsx
  src/components/Search/InstantSearch.tsx
  src/components/Section/AIRecommendationSection.tsx
  src/components/Section/UserPreferredSection.tsx
  src/hooks/useCartCount.tsx
  src/hooks/useEventTracker.tsx
  src/hooks/useExcludeRecommedation.ts
  src/pages/[genre]/index.tsx
  src/services/accounts/request.ts
  src/services/books/request.ts
  src/services/category/request.ts
  src/services/notification/request.ts
  src/utils/axiosInterceptors.ts
  src/utils/sentry.ts
Labels: bug, chore

#136 Hotfix/퀵메뉴 트래킹 파라미터 추가
  src/components/QuickMenu/QuickMenuList.tsx
Labels: hotfix, temporary, tracking

#135 Fix/profile-live-step
  .circleci/config.yml
Labels: testing

#128 다른 장르에서 일반 장르로 이동할 때 리로드하는 현상 수정
  src/components/GNB/HomeLink.tsx
  src/components/GNB/index.tsx
  src/components/Tabs/GenreTab.tsx
  src/components/Tabs/MainTab.tsx
  src/pages/[genre]/index.tsx
  src/tests/components/Tabs/MainTab.spec.tsx
Labels: enhancement, experimental, refactor

#131 RecommendedBook 정리
  src/components/RecommendedBook/BookMeta.tsx
  src/components/RecommendedBook/RecommendedBook.tsx
  src/components/RecommendedBook/RecommendedBookCarousel.tsx
  src/components/RecommendedBook/RecommendedBookItem.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
  src/components/RecommendedBook/index.ts
  src/components/RecommendedBook/index.tsx
  src/components/RecommendedBook/types.ts
  src/components/Section/HomeSectionRenderer.tsx
  src/hooks/useBookDetailSelector.ts
  src/tests/components/RecommendedBook/RecommendedBook.spec.tsx
  src/utils/highlight.ts
Labels: refactor

#141 다크 오리발 첫 렌더 여백 수정
  src/components/RecommendedBook/RecommendedBookList.tsx
Labels: styling

#142 한번 로드한 썸네일은 표시 유지함
  src/components/BookThumbnail/ThumbnailRenderer.tsx
Labels: enhancement, styling

#143 Circle CI workspace 보관 기간이 짧아서 롤백을 하지 못하는 문제 수정
  .circleci/config.yml
Labels: CI/CD

#144 이전 릴리즈 timestamp 기록을 yarn install 이후로 이동
  .circleci/config.yml
Labels: CI/CD

#139 USE_CSR=true인 경우 마지막 이용 장르로 전환
  next.config.js
  src/components/GNB/HomeLink.tsx
  src/components/Tabs/GenreTab.tsx
  src/components/Tabs/MainTab.tsx
  src/pages/[genre]/index.tsx
Labels: chore

#147 Hotfix/fix badge line height
  src/components/TopBanner.tsx
Labels: hotfix

#146 Added DisallowedHostsFilter component
  src/components/Misc/DisallowedHostsFilter.tsx
  src/pages/_app.tsx
Labels: hotfix

#150 Nextjs 판올림
  package.json
  yarn.lock
Labels: chore

#151 link-name audit 경고로 변경
  lighthouserc.json
Labels: a11y, chore

#152 hotfix/책 상세 페이지에서 카테고리 아이콘 style 수정
  src/components/Tabs/GenreTab.tsx
Labels: hotfix, styling

#154 Hotfix: last_sub_service localStorage data validate
  src/components/Tabs/GenreTab.tsx
Labels: hotfix

#157 Update /manifest.webmanifest url
  src/components/Meta/index.tsx
Labels: hotfix

#156 더 이상 사용하지 않는 <BrowserLocationContext/> 삭제
  src/components/Context/BrowserLocation.tsx
  src/components/Context/index.ts
  src/pages/_app.tsx
  src/pages/partials/gnb/index.tsx
  src/tests/pages/[genre].spec.tsx
Labels: chore, refactor

#160 books.ridi.io/general 또는 books.ridibooks.com/general 접근 시 무한 리다이렉트 수정
  next.config.js
Labels: bug, chore

#161 Rename: `NEXT_STATIC_SENTRY_DSN` -> `SENTRY_DSN`
  next.config.js
  src/utils/sentry.ts
Labels: CI/CD, chore

#162 프로젝트 이름을 올바르게 변경
  .sentryclirc
Labels: CI/CD, chore

#159 Hotfix/배지 잘림, 오리발 간격, 추천 제외 버튼 등 자잘한 스타일을 수정합니다.
  src/components/BookSections/SelectionBook/SelectionBook.tsx
  src/components/Carousel/BooksCarousel.tsx
  src/components/RecommendedBook/RecommendedBookItem.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
  src/tests/components/BookSelections/SelectionBook.spec.tsx
Labels: hotfix, styling

#163 IE11 폴리필 수정
  .babelrc.js
  next.config.js
  package.json
  src/components/KeywordFinder/HomeKeywordFinderSection.tsx
  src/pages/_app.tsx
  src/polyfills.js
  yarn.lock
Labels: chore

#165 Next.js 판 올림 9.3.2
  package.json
  yarn.lock
Labels: chore, security

#140 테스트 할 때 발생하는 next/router 오류 수정
  src/components/Section/HomeSectionRenderer.tsx
  src/hooks/useIntersectionObserver.ts
  src/pages/[genre]/index.tsx
  src/tests/components/Tabs/GenreTab.spec.tsx
  src/tests/components/Tabs/MainTab.spec.tsx
  src/tests/pages/GenreHome.spec.tsx
  src/tests/pages/[genre].spec.tsx
  src/tests/pages/__App.spec.tsx
  src/tests/pages/home-bl-fixture.json
  src/tests/pages/home-fantasy-fixture.json
  src/tests/pages/partials/gnb/Index.spec.tsx
Labels: testing

#166 강제 리플로우 제거
  src/components/BookSections/RankingBook/RankingBookList.tsx
  src/components/BookSections/SelectionBook/SelectionBookList.tsx
  src/components/KeywordFinder/HomeKeywordFinderSection.tsx
  src/components/QuickMenu/QuickMenuList.tsx
  src/components/RecommendedBook/RecommendedBookList.tsx
  src/components/ScrollContainer.tsx
  src/components/TopBanner.tsx
  src/hooks/useScrollPosition.ts
  src/hooks/useScrollSlider.ts
  src/tests/components/ScrollContainer.spec.tsx
  src/tests/hooks/useViewportIntersection.spec.tsx
  src/tests/utils/MockIO.ts
  src/types/grid.d.ts
  src/types/svg.d.ts
Labels: enhancement

#171 hotfix/알림 unread_count 호출하지 않는 문제 수정
  src/components/Tabs/MainTab.tsx
Labels: hotfix

#167 theme cookie값 ssr시 가져오도록 변경
  package.json
  src/components/GNB/HomeLink.tsx
  src/components/Misc/InAppThemeProvider.tsx
  src/components/Tabs/GenreTab.tsx
  src/components/Tabs/MainTab.tsx
  src/constants/cookies.ts
  src/pages/[genre]/index.tsx
  src/pages/_app.tsx
  src/pages/notification/index.tsx
  src/services/notification/saga.ts
  src/tests/pages/__App.spec.tsx
  yarn.lock
Labels: chore, styling

#173 hotfix/일반 장르 탭 href를 '/general' 로 변경
  src/components/Tabs/GenreTab.tsx
Labels: hotfix

#176 쿠키에 path=/ 추가
  src/components/Tabs/GenreTab.tsx
  src/services/notification/saga.ts
Labels: bug

#170 센트리 초기화 및 호출부분 수정
  jest.config.js
  next.config.js
  package.json
  src/components/GNB/index.tsx
  src/components/Search/InstantSearch.tsx
  src/components/Section/AIRecommendationSection.tsx
  src/components/Section/UserPreferredSection.tsx
  src/hooks/useCartCount.tsx
  src/hooks/useEventTracker.tsx
  src/hooks/useExcludeRecommedation.ts
  src/pages/[genre]/index.tsx
  src/pages/_app.tsx
  src/pages/_error.tsx
  src/pages/notification/index.tsx
  src/services/books/reducer.ts
  src/services/books/request.ts
  src/services/books/saga.ts
  src/services/category/saga.ts
  src/services/notification/saga.ts
  src/tests/__mocks__/mockModules.tsx
  src/utils/bookTitleGenerator.ts
  src/utils/sentry.ts
  yarn.lock
Labels: chore
